[workspace]
members = [
    "core",
    # "debug",
    "rapier",
    "macros"
]

[package]
name = "heron"
version = "0.11.0" # auto-version
authors = ["Jonathan Cornaz"]
edition = "2018"
license = "MIT"
description = "An ergonomic physics API for 2d and 3d bevy games. (powered by rapier)"
repository = "https://github.com/jcornaz/heron/"
keywords = ["game", "gamedev", "physics", "collision", "bevy"]
categories = ["game-development", "simulation"]
resolver = "2"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
2d = ["heron_rapier/2d"]
3d = ["heron_rapier/3d"]
# debug-2d = ["2d", "heron_debug/2d"]

[dependencies]
heron_core = { version = "^0.11.0", path = "core" }
heron_macros = { version = "^0.11.0", path = "macros" }
heron_rapier = { version = "^0.11.0", path = "rapier" }
alsa = "=0.5.0"
# heron_debug = { version = "^0.11.0", path = "debug", optional = true }
# bevy = { git = "https://github.com/katharostech/bevy", branch = "bevy_retrograde_0.3", default-features = false }

[dev-dependencies]
# bevy = { git = "https://github.com/katharostech/bevy", branch = "bevy_retrograde_0.3" }
skeptic = "0.13"
rstest = "0.7"

[dev-dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev="6a8a8c9d21f32e0e46623db9438813b009f9e014"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev="6a8a8c9d21f32e0e46623db9438813b009f9e014"

[build-dependencies]
cfg_aliases = "0.1.1"

[[example]]
name = "demo"
required-features = ["2d"]

# [[example]]
# name = "debug"
# required-features = ["debug-2d"]

[[example]]
name = "quickstart"
required-features = ["2d"]

# [[example]]
# name = "collision_shapes_in_child_entity"
# required-features = ["debug-2d"]

[[example]]
name = "layers"
required-features = ["2d"]

[[example]]
name = "events"
required-features = ["2d"]

[[example]]
name = "ray_casting"
required-features = ["2d"]
